services:
  postgres:
    image: "postgres:17.1-alpine"
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - "./target/data/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indexer"]
      interval: "5s"
      timeout: "2s"
      retries: 2
